### ISSUE TITLE
idk how to install this theme

### ISSUE THREAD

**Issue by Razuuu** [RafaelDeJongh/h5ai-dark-theme#4]
^

**Comment by RafaelDeJongh** [comment]
You do this by copy pasting the code to the end of the original. Until there is any form of theme support. This is the easiest solution to add a theme and/or modify the default theme.

**Comment by Razuuu** [comment]
i do this but is buggy half is white and half is dark

**Comment by Razuuu** [comment]
okay sorry my mistake... it works
